/**
 * Supabase Types
 * Central export for all Supabase-related types
 */

// Re-export database types generated by Supabase CLI
export * from './database.types'
export type { Database } from './database.types'

// Custom domain types that extend database types
export interface VehicleWithOwner {
  id: string
  owner_id: string
  type: 'scooter' | 'motorcycle' | 'car' | 'van'
  make: string | null
  model: string | null
  year: number | null
  plate_number: string
  description: string | null
  price_per_day: number
  price_per_week: number | null
  price_per_month: number | null
  status: 'available' | 'rented' | 'maintenance' | 'inactive'
  location: string | null
  image_urls: string[]
  features: Record<string, any>
  rental_terms: string | null
  transmission: 'manual' | 'automatic' | null
  fuel_type: 'gasoline' | 'diesel' | 'electric' | 'hybrid' | null
  is_approved: boolean
  admin_notes: string | null
  created_at: string
  updated_at: string
  owner: {
    id: string
    full_name: string | null
    profile_image_url: string | null
    phone_number?: string | null
  } | null
}

export interface BookingWithDetails {
  id: string
  renter_id: string
  vehicle_id: string
  owner_id: string
  start_date: string
  end_date: string
  total_price: number
  status: 'pending' | 'confirmed' | 'active' | 'completed' | 'cancelled'
  pickup_time: string | null
  return_time: string | null
  pickup_location: string | null
  return_location: string | null
  special_requests: string | null
  cancellation_reason: string | null
  created_at: string
  updated_at: string
  vehicle?: any
  renter?: any
  payment?: any
}

export interface ReviewWithDetails {
  id: string
  booking_id: string
  reviewer_id: string
  vehicle_id: string
  owner_id: string
  rating: number
  comment: string | null
  cleanliness_rating: number | null
  condition_rating: number | null
  value_rating: number | null
  communication_rating: number | null
  is_approved: boolean
  created_at: string
  updated_at: string
  reviewer?: {
    id: string
    full_name: string | null
    profile_image_url: string | null
  }
  vehicle?: {
    id: string
    type: string
    make: string | null
    model: string | null
  }
}

export interface MessageWithSender {
  id: string
  booking_id: string
  sender_id: string
  receiver_id: string
  content: string
  is_read: boolean
  created_at: string
  sender?: {
    id: string
    full_name: string | null
    profile_image_url: string | null
    email: string
  }
}

export interface NotificationData {
  id: string
  user_id: string
  type: 'booking' | 'payment' | 'message' | 'review' | 'system'
  title: string
  message: string
  link: string | null
  is_read: boolean
  created_at: string
}

// Query filter types
export interface VehicleFilters {
  type?: string | string[]
  minPrice?: number
  maxPrice?: number
  location?: string
  startDate?: string
  endDate?: string
  searchQuery?: string
  transmission?: 'manual' | 'automatic'
  fuelType?: 'gasoline' | 'diesel' | 'electric' | 'hybrid'
}

export interface BookingFilters {
  status?: 'pending' | 'confirmed' | 'active' | 'completed' | 'cancelled'
  startDate?: string
  endDate?: string
}

// API Response types
export interface PaginatedResponse<T> {
  data: T[]
  total: number
  page: number
  limit: number
  hasMore: boolean
}

export interface ApiError {
  message: string
  code?: string
  details?: any
}

export interface ApiResponse<T = any> {
  data?: T
  error?: ApiError
  success: boolean
}
