// This file is auto-generated by Supabase. In production, run: npm run supabase:gen-types
// For now, this is a manual type definition based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          full_name: string | null
          phone_number: string | null
          role: 'renter' | 'owner' | 'admin'
          profile_image_url: string | null
          is_verified: boolean
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          phone_number?: string | null
          role?: 'renter' | 'owner' | 'admin'
          profile_image_url?: string | null
          is_verified?: boolean
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          phone_number?: string | null
          role?: 'renter' | 'owner' | 'admin'
          profile_image_url?: string | null
          is_verified?: boolean
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      vehicles: {
        Row: {
          id: string
          owner_id: string
          type: 'scooter' | 'motorcycle' | 'car' | 'van'
          make: string | null
          model: string | null
          year: number | null
          plate_number: string
          description: string | null
          price_per_day: number
          price_per_week: number | null
          price_per_month: number | null
          status: 'available' | 'rented' | 'maintenance' | 'inactive'
          location: string | null
          image_urls: string[]
          features: Json
          rental_terms: string | null
          is_approved: boolean
          admin_notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          type: 'scooter' | 'motorcycle' | 'car' | 'van'
          make?: string | null
          model?: string | null
          year?: number | null
          plate_number: string
          description?: string | null
          price_per_day: number
          price_per_week?: number | null
          price_per_month?: number | null
          status?: 'available' | 'rented' | 'maintenance' | 'inactive'
          location?: string | null
          image_urls?: string[]
          features?: Json
          rental_terms?: string | null
          is_approved?: boolean
          admin_notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          type?: 'scooter' | 'motorcycle' | 'car' | 'van'
          make?: string | null
          model?: string | null
          year?: number | null
          plate_number?: string
          description?: string | null
          price_per_day?: number
          price_per_week?: number | null
          price_per_month?: number | null
          status?: 'available' | 'rented' | 'maintenance' | 'inactive'
          location?: string | null
          image_urls?: string[]
          features?: Json
          rental_terms?: string | null
          is_approved?: boolean
          admin_notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      bookings: {
        Row: {
          id: string
          renter_id: string
          vehicle_id: string
          start_date: string
          end_date: string
          total_price: number
          status: 'pending' | 'confirmed' | 'active' | 'completed' | 'cancelled'
          pickup_time: string | null
          return_time: string | null
          special_requests: string | null
          renter_notes: string | null
          owner_notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          renter_id: string
          vehicle_id: string
          start_date: string
          end_date: string
          total_price: number
          status?: 'pending' | 'confirmed' | 'active' | 'completed' | 'cancelled'
          pickup_time?: string | null
          return_time?: string | null
          special_requests?: string | null
          renter_notes?: string | null
          owner_notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          renter_id?: string
          vehicle_id?: string
          start_date?: string
          end_date?: string
          total_price?: number
          status?: 'pending' | 'confirmed' | 'active' | 'completed' | 'cancelled'
          pickup_time?: string | null
          return_time?: string | null
          special_requests?: string | null
          renter_notes?: string | null
          owner_notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      payments: {
        Row: {
          id: string
          booking_id: string
          amount: number
          payment_method: 'gcash' | 'maya' | 'card' | 'bank_transfer'
          status: 'pending' | 'paid' | 'failed' | 'refunded'
          transaction_id: string | null
          gateway_response: Json | null
          refund_amount: number
          refund_reason: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          booking_id: string
          amount: number
          payment_method: 'gcash' | 'maya' | 'card' | 'bank_transfer'
          status?: 'pending' | 'paid' | 'failed' | 'refunded'
          transaction_id?: string | null
          gateway_response?: Json | null
          refund_amount?: number
          refund_reason?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          booking_id?: string
          amount?: number
          payment_method?: 'gcash' | 'maya' | 'card' | 'bank_transfer'
          status?: 'pending' | 'paid' | 'failed' | 'refunded'
          transaction_id?: string | null
          gateway_response?: Json | null
          refund_amount?: number
          refund_reason?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      reviews: {
        Row: {
          id: string
          booking_id: string
          reviewer_id: string
          vehicle_id: string
          rating: number
          cleanliness_rating: number | null
          condition_rating: number | null
          value_rating: number | null
          comment: string | null
          image_urls: string[]
          is_approved: boolean
          is_flagged: boolean
          admin_notes: string | null
          owner_response: string | null
          owner_response_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          booking_id: string
          reviewer_id: string
          vehicle_id: string
          rating: number
          cleanliness_rating?: number | null
          condition_rating?: number | null
          value_rating?: number | null
          comment?: string | null
          image_urls?: string[]
          is_approved?: boolean
          is_flagged?: boolean
          admin_notes?: string | null
          owner_response?: string | null
          owner_response_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          booking_id?: string
          reviewer_id?: string
          vehicle_id?: string
          rating?: number
          cleanliness_rating?: number | null
          condition_rating?: number | null
          value_rating?: number | null
          comment?: string | null
          image_urls?: string[]
          is_approved?: boolean
          is_flagged?: boolean
          admin_notes?: string | null
          owner_response?: string | null
          owner_response_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      maintenance_logs: {
        Row: {
          id: string
          vehicle_id: string
          service_date: string
          service_type: string
          description: string | null
          cost: number | null
          service_provider: string | null
          next_service_date: string | null
          odometer_reading: number | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          vehicle_id: string
          service_date: string
          service_type: string
          description?: string | null
          cost?: number | null
          service_provider?: string | null
          next_service_date?: string | null
          odometer_reading?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          vehicle_id?: string
          service_date?: string
          service_type?: string
          description?: string | null
          cost?: number | null
          service_provider?: string | null
          next_service_date?: string | null
          odometer_reading?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      messages: {
        Row: {
          id: string
          booking_id: string
          sender_id: string
          content: string
          image_urls: string[]
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          booking_id: string
          sender_id: string
          content: string
          image_urls?: string[]
          is_read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          booking_id?: string
          sender_id?: string
          content?: string
          image_urls?: string[]
          is_read?: boolean
          created_at?: string
        }
      }
      favorites: {
        Row: {
          id: string
          user_id: string
          vehicle_id: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          vehicle_id: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          vehicle_id?: string
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          title: string
          message: string
          type: string
          related_id: string | null
          is_read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          message: string
          type: string
          related_id?: string | null
          is_read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          message?: string
          type?: string
          related_id?: string | null
          is_read?: boolean
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      user_role: 'renter' | 'owner' | 'admin'
      vehicle_type: 'scooter' | 'motorcycle' | 'car' | 'van'
      vehicle_status: 'available' | 'rented' | 'maintenance' | 'inactive'
      booking_status: 'pending' | 'confirmed' | 'active' | 'completed' | 'cancelled'
      payment_status: 'pending' | 'paid' | 'failed' | 'refunded'
      payment_method: 'gcash' | 'maya' | 'card' | 'bank_transfer'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

